[project]
name = "swift-evolution-updates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx==0.27.2",
    "openai==1.16.1",
    "python-dotenv==1.0.1",
]
